<template>
  <div class="expert-tab">
    <!-- Capture quality assessment -->
    <el-card shadow="never" v-if="assessment">
      <template #header>
        <div class="card-header">
          <span class="card-title">Capture Quality Assessment</span>
          <el-tag :type="qualityType" effect="dark" size="small">
            {{ assessment.quality_label }}
          </el-tag>
        </div>
      </template>

      <div class="assessment-grid">
        <div class="asses-col">
          <div class="col-title danger-title">Issues Detected</div>
          <ul class="assess-list" v-if="assessment.issues.length">
            <li v-for="(s, i) in assessment.issues" :key="i">{{ s }}</li>
          </ul>
          <p class="no-items" v-else>No capture quality issues detected.</p>
        </div>

        <div class="asses-col">
          <div class="col-title success-title">Directly Observed (reliable)</div>
          <ul class="assess-list success">
            <li v-for="(s, i) in assessment.reliable" :key="i">{{ s }}</li>
          </ul>
        </div>

        <div class="asses-col">
          <div class="col-title warn-title">Low Confidence</div>
          <ul class="assess-list warn" v-if="assessment.low_confidence.length">
            <li v-for="(s, i) in assessment.low_confidence" :key="i">{{ s }}</li>
          </ul>
          <p class="no-items" v-else>All conclusions have adequate confidence.</p>
        </div>

        <div class="asses-col">
          <div class="col-title info-title">Inferred (not directly stated)</div>
          <ul class="assess-list info">
            <li v-for="(s, i) in assessment.inferred" :key="i">{{ s }}</li>
          </ul>
        </div>
      </div>

      <!-- Stats summary -->
      <div class="quality-stats">
        <div class="qs-chip">
          <span class="qs-val">{{ assessment.total_sessions }}</span>
          <span class="qs-lbl">Total Sessions</span>
        </div>
        <div class="qs-chip warn" v-if="assessment.midstream_count > 0">
          <span class="qs-val">{{ assessment.midstream_count }} ({{ assessment.midstream_pct }}%)</span>
          <span class="qs-lbl">Mid-stream</span>
        </div>
        <div class="qs-chip danger" v-if="assessment.failed_handshake_count > 0">
          <span class="qs-val">{{ assessment.failed_handshake_count }}</span>
          <span class="qs-lbl">Failed Handshakes</span>
        </div>
        <div class="qs-chip warn" v-if="assessment.no_close_count > 0">
          <span class="qs-val">{{ assessment.no_close_count }}</span>
          <span class="qs-lbl">No Close Observed</span>
        </div>
      </div>
    </el-card>

    <!-- tshark expert info -->
    <el-card shadow="never" class="mt-3" v-if="expertInfo?.length">
      <template #header>
        <span class="card-title">tshark Expert Analyzer Output</span>
      </template>
      <el-table :data="expertInfo" size="small" stripe>
        <el-table-column prop="severity" label="Level" width="90">
          <template #default="{ row }">
            <el-tag :type="expertTagType(row.severity)" size="small">
              {{ row.severity }}
            </el-tag>
          </template>
        </el-table-column>
        <el-table-column prop="count" label="Count" width="80" sortable />
        <el-table-column prop="message" label="Message" />
      </el-table>
    </el-card>

    <!-- Honest disclaimer -->
    <el-card shadow="never" class="mt-3 disclaimer-card">
      <template #header><span class="card-title">Analysis Limitations</span></template>
      <ul class="disclaimer-list">
        <li>Protocol identification is based on port numbers and application-layer markers. Without application data (e.g., TLS-encrypted sessions), protocol labels are <strong>inferred</strong>, not confirmed.</li>
        <li>Host role classification (client/server/gateway) is derived from connection patterns and is <strong>not authoritative</strong>.</li>
        <li>Security findings are generated by rule-based heuristics. They indicate suspicion, not forensic certainty. Findings must be validated by an analyst.</li>
        <li>For mid-stream sessions, session start time, intent, and handshake details <strong>cannot be confirmed</strong> from this capture alone.</li>
        <li>TLS payload content is encrypted and is <strong>not visible</strong> in this analysis. Only TLS metadata (SNI, version, cipher, JA3) is available.</li>
      </ul>
    </el-card>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import type { CaptureAssessment, ExpertInfo } from '@/types/analysis'

const props = defineProps<{
  assessment: CaptureAssessment | null
  expertInfo: ExpertInfo[]
}>()

const qualityType = computed(() => {
  const q = props.assessment?.quality
  if (q === 'good') return 'success'
  if (q === 'partial') return 'warning'
  if (q === 'poor') return 'danger'
  return 'info'
})

function expertTagType(sev: string): string {
  if (sev === 'error') return 'danger'
  if (sev === 'warn') return 'warning'
  if (sev === 'note') return 'info'
  return ''
}
</script>

<style scoped>
.expert-tab { display: flex; flex-direction: column; gap: 12px; }
.card-title { font-weight: 600; font-size: 14px; }
.card-header { display: flex; align-items: center; gap: 10px; }
.mt-3 { margin-top: 0; }

.assessment-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 16px; margin-bottom: 16px; }
@media (max-width: 800px) { .assessment-grid { grid-template-columns: 1fr; } }

.asses-col {}
.col-title {
  font-size: 12px; font-weight: 700; text-transform: uppercase;
  letter-spacing: .05em; margin-bottom: 6px; padding-bottom: 4px;
  border-bottom: 2px solid currentColor;
}
.danger-title { color: #f56c6c; }
.success-title { color: #67c23a; }
.warn-title { color: #e6a23c; }
.info-title { color: #409eff; }

.assess-list { margin: 0; padding-left: 18px; font-size: 13px; line-height: 1.8; color: #606266; }
.assess-list.success li::marker { color: #67c23a; }
.assess-list.warn li::marker { color: #e6a23c; }
.assess-list.info li::marker { color: #409eff; }
.no-items { font-size: 13px; color: #909399; margin: 0; }

.quality-stats { display: flex; flex-wrap: wrap; gap: 10px; margin-top: 8px; }
.qs-chip {
  background: #f5f7fa; border-radius: 6px; padding: 8px 14px; text-align: center;
}
.qs-chip.warn  { background: #fdf6ec; }
.qs-chip.danger { background: #fef0f0; }
.qs-val { display: block; font-size: 16px; font-weight: 700; color: #303133; }
.qs-chip.warn  .qs-val { color: #e6a23c; }
.qs-chip.danger .qs-val { color: #f56c6c; }
.qs-lbl { font-size: 11px; color: #909399; }

.disclaimer-card { border-color: #ebeef5; }
.disclaimer-list { margin: 0; padding-left: 20px; font-size: 13px; color: #606266; line-height: 1.9; }
.disclaimer-list li { margin-bottom: 4px; }
</style>
